apiVersion: v1

kind: Pod

metadata:

  labels:

    jenkins-agent: terraform

spec:

  serviceAccountName: jenkins

  containers:

    - name: terraform

      image: terraform-eks-agent:latest

      command:

        - cat

      tty: true

      resources:

        limits:

          cpu: "2"

          memory: "4Gi"

        requests:

          cpu: "1"

          memory: "2Gi"

          